* Running calibration study

** Getting help

The computations are coordinated with Ant. To get a list of the various targets
it knows how to build run the following:

#+begin_src sh
  ant -p
#+end_src

** Setting up BEAST2

#+begin_src sh
  ant setuplib
#+end_src

Note that this will only set up the relevant BEAST tools. You will still need to
install the TimTam package via BEAUti.

** Running study

#+begin_src sh
  ant scenario-3
#+end_src

The =scenario-3= target carries out the whole computation. This is just a
wrapper around the sub-targets:

- =scenario-3-remaster= :: Runs the =remaster= simulation.
- =scenario-3-preprocess= :: Simulates the genetic data and constructs the BEAST
  XML for the MCMC.
- =scenario-3-mcmc= :: Runs the MCMC replicates in parallel across several
  batches.
- =scenario-3-postprocess= :: Post-processing of posterior samples and figure
  generation.

The output should appear in the =out/s3= directory.

* Simulation study

** Scenario 1

| Parameter   | Description             | Value |
|-------------+-------------------------+-------|
| \(\lambda\) | Birth rate              | 0.185 |
| \(\mu\)     | Death rate              | 0.046 |
| \(\psi\)    | Sampling rate           | 0.008 |
| \(\omega\)  | Occurrence rate         | 0.046 |
|             | Duration                |    42 |
| \(\rho\)    | Catastrophe probability |   0.5 |

** Scenario 2

| Parameter   | Description     | Value |
|-------------+-----------------+-------|
| \(\lambda\) | Birth rate      | 0.185 |
| \(\mu\)     | Death rate      | 0.046 |
| \(\psi\)    | Sampling rate   | 0.008 |
| \(\omega\)  | Occurrence rate | 0.046 |
|             | Duration        |    42 |

*** Analysis 1

Assuming birth-death model is correctly specified and only estimating the rates.

*** Analysis 2

Assuming birth-death model is correctly specified and estimating both the rates
and the prevalence just after the last sample (at time \(-0.01\)).

** Scenario 3

| Parameter     | Description            |  Value |
|---------------+------------------------+--------|
|               | Duration               |     56 |
| \(\lambda_1\) | Birth rate 1           |  0.185 |
| \(\lambda_2\) | Birth rate 2           | 0.0925 |
|               | Birth rate change time |     42 |
| \(\mu\)       | Death rate             |  0.046 |
| \(\psi\)      | Sampling rate          |  0.008 |
| \(\omega\)    | Occurrence rate        |  0.046 |

*** Analysis 1

Assuming birth-death model is correctly specified and only estimating the rates.

*** Analysis 2

Assuming birth-death model is correctly specified and estimating both the rates
and the prevalence just after the last sample (at time \(-0.01\)).

*** Analysis 3

Use the canonical parameterisation and estimate the prevalence just after the
last sample (at time \(-0.01\)), but aggregate the occurrence data into daily
counts.
